name: Compile CLI And Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build binaries
        run: npm run pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ./bin/ctf_linux_amd64
            ./bin/ctf_darwin_arm64
          if-no-files-found: error
          retention-days: 1

  release:
    needs: compile
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/ctf_*"
