name: Compile CLI And Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build Linux binary
        run: npm run pkg

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: bin/ctf_linux_amd64
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build macOS binary
        run: |
          npm run pkg
          chmod +x ./bin/ctf_darwin_arm64
          codesign --force --sign - ./bin/ctf_darwin_arm64

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: bin/ctf_darwin_arm64
          if-no-files-found: error

  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-binaries'
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/ctf_*"
